import type { AuditLog } from '@/features/auditLogs/types/auditLog';

export const mockAuditLogs: AuditLog[] = [
  {
    log_id: 12001,
    user_id: 10,
    username: 'superadmin',
    role: 'Admin',
    action: 'UPDATED_PATIENT_RECORD',
    entity_type: 'PATIENT',
    entity_id: 1001,
    description: 'Updated emergency contact number',
    ip_address: '192.168.1.24',
    severity: 'Info',
    created_at: '2026-04-26 14:35:00'
  },
  {
    log_id: 12002,
    user_id: 15,
    username: 'dr.smith',
    role: 'Doctor',
    action: 'VIEWED_MEDICAL_RECORD',
    entity_type: 'MEDICAL_RECORD',
    entity_id: 2005,
    description: 'Accessed patient medical history',
    ip_address: '192.168.1.45',
    severity: 'Info',
    created_at: '2026-04-26 14:28:00'
  },
  {
    log_id: 12003,
    user_id: 20,
    username: 'nurse.jones',
    role: 'Nurse',
    action: 'LOGIN_FAILED',
    entity_type: 'LOGIN',
    entity_id: 0,
    description: 'Failed login attempt - invalid password',
    ip_address: '192.168.1.67',
    severity: 'Warning',
    created_at: '2026-04-26 14:20:00'
  },
  {
    log_id: 12004,
    user_id: 10,
    username: 'superadmin',
    role: 'Admin',
    action: 'DELETED_USER_ACCOUNT',
    entity_type: 'USER',
    entity_id: 25,
    description: 'Permanently deleted nurse account',
    ip_address: '192.168.1.24',
    severity: 'Critical',
    created_at: '2026-04-26 14:15:00'
  },
  {
    log_id: 12005,
    user_id: 16,
    username: 'dr.brown',
    role: 'Doctor',
    action: 'SCHEDULED_APPOINTMENT',
    entity_type: 'APPOINTMENT',
    entity_id: 3002,
    description: 'Created new appointment for patient',
    ip_address: '192.168.1.89',
    severity: 'Info',
    created_at: '2026-04-26 14:10:00'
  },
  {
    log_id: 12006,
    user_id: 21,
    username: 'nurse.davis',
    role: 'Nurse',
    action: 'UPDATED_MEDICAL_RECORD',
    entity_type: 'MEDICAL_RECORD',
    entity_id: 2010,
    description: 'Added vital signs measurement',
    ip_address: '192.168.1.12',
    severity: 'Info',
    created_at: '2026-04-26 14:05:00'
  },
  {
    log_id: 12007,
    user_id: 22,
    username: 'nurse.wilson',
    role: 'Nurse',
    action: 'LOGIN_FAILED',
    entity_type: 'LOGIN',
    entity_id: 0,
    description: 'Failed login attempt - account locked',
    ip_address: '192.168.1.34',
    severity: 'Warning',
    created_at: '2026-04-26 13:55:00'
  },
  {
    log_id: 12008,
    user_id: 10,
    username: 'superadmin',
    role: 'Admin',
    action: 'MODIFIED_SYSTEM_SETTINGS',
    entity_type: 'SYSTEM_SETTING',
    entity_id: 1,
    description: 'Changed password policy requirements',
    ip_address: '192.168.1.24',
    severity: 'Critical',
    created_at: '2026-04-26 13:45:00'
  },
  {
    log_id: 12009,
    user_id: 17,
    username: 'dr.garcia',
    role: 'Doctor',
    action: 'GENERATED_REPORT',
    entity_type: 'REPORT',
    entity_id: 4001,
    description: 'Exported monthly patient statistics',
    ip_address: '192.168.1.56',
    severity: 'Info',
    created_at: '2026-04-26 13:30:00'
  },
  {
    log_id: 12010,
    user_id: 23,
    username: 'nurse.miller',
    role: 'Nurse',
    action: 'LOGIN_FAILED',
    entity_type: 'LOGIN',
    entity_id: 0,
    description: 'Failed login attempt - wrong username',
    ip_address: '192.168.1.78',
    severity: 'Warning',
    created_at: '2026-04-26 13:25:00'
  },
  {
    log_id: 12011,
    user_id: 10,
    username: 'superadmin',
    role: 'Admin',
    action: 'EXPORTED_AUDIT_LOGS',
    entity_type: 'SECURITY',
    entity_id: 0,
    description: 'Exported audit logs for compliance review',
    ip_address: '192.168.1.24',
    severity: 'Info',
    created_at: '2026-04-26 13:15:00'
  },
  {
    log_id: 12012,
    user_id: 18,
    username: 'dr.taylor',
    role: 'Doctor',
    action: 'CANCELLED_APPOINTMENT',
    entity_type: 'APPOINTMENT',
    entity_id: 3005,
    description: 'Cancelled patient appointment',
    ip_address: '192.168.1.90',
    severity: 'Warning',
    created_at: '2026-04-26 13:10:00'
  },
  {
    log_id: 12013,
    user_id: 24,
    username: 'nurse.anderson',
    role: 'Nurse',
    action: 'VIEWED_PATIENT_RECORD',
    entity_type: 'PATIENT',
    entity_id: 1005,
    description: 'Accessed patient demographic information',
    ip_address: '192.168.1.23',
    severity: 'Info',
    created_at: '2026-04-26 13:05:00'
  },
  {
    log_id: 12014,
    user_id: 19,
    username: 'dr.martinez',
    role: 'Doctor',
    action: 'UPDATED_MEDICAL_RECORD',
    entity_type: 'MEDICAL_RECORD',
    entity_id: 2015,
    description: 'Added prescription information',
    ip_address: '192.168.1.67',
    severity: 'Info',
    created_at: '2026-04-26 12:50:00'
  },
  {
    log_id: 12015,
    user_id: 25,
    username: 'nurse.thomas',
    role: 'Nurse',
    action: 'LOGIN_FAILED',
    entity_type: 'LOGIN',
    entity_id: 0,
    description: 'Failed login attempt - expired session',
    ip_address: '192.168.1.45',
    severity: 'Warning',
    created_at: '2026-04-26 12:40:00'
  },
  {
    log_id: 12016,
    user_id: 10,
    username: 'superadmin',
    role: 'Admin',
    action: 'CREATED_USER_ACCOUNT',
    entity_type: 'USER',
    entity_id: 26,
    description: 'Created new doctor account',
    ip_address: '192.168.1.24',
    severity: 'Info',
    created_at: '2026-04-26 12:30:00'
  },
  {
    log_id: 12017,
    user_id: 20,
    username: 'nurse.jones',
    role: 'Nurse',
    action: 'RESET_PASSWORD',
    entity_type: 'USER',
    entity_id: 20,
    description: 'Password reset requested',
    ip_address: '192.168.1.67',
    severity: 'Warning',
    created_at: '2026-04-26 12:20:00'
  },
  {
    log_id: 12018,
    user_id: 11,
    username: 'admin.rivera',
    role: 'Admin',
    action: 'VIEWED_AUDIT_LOGS',
    entity_type: 'SECURITY',
    entity_id: 0,
    description: 'Reviewed security audit logs',
    ip_address: '192.168.1.12',
    severity: 'Info',
    created_at: '2026-04-26 12:10:00'
  },
  {
    log_id: 12019,
    user_id: 26,
    username: 'dr.newman',
    role: 'Doctor',
    action: 'LOGIN_SUCCESSFUL',
    entity_type: 'LOGIN',
    entity_id: 0,
    description: 'Successful login to system',
    ip_address: '192.168.1.89',
    severity: 'Info',
    created_at: '2026-04-26 12:00:00'
  },
  {
    log_id: 12020,
    user_id: 27,
    username: 'nurse.clark',
    role: 'Nurse',
    action: 'UPDATED_PATIENT_RECORD',
    entity_type: 'PATIENT',
    entity_id: 1010,
    description: 'Updated patient contact information',
    ip_address: '192.168.1.34',
    severity: 'Info',
    created_at: '2026-04-26 11:50:00'
  }
];