import type { AssignmentRecord, DoctorProfile, PatientSummary, PatientStatus } from '@/features/doctorAssignments/types/assignment';

export const doctorProfiles: DoctorProfile[] = [
  { doctor_id: 12, doctor_name: 'Dr. Antonio Garcia', specialization: 'Cardiology', is_active: true, active_patients: 18, current_load: 18 },
  { doctor_id: 17, doctor_name: 'Dr. Leila Santos', specialization: 'Pulmonology', is_active: true, active_patients: 10, current_load: 10 },
  { doctor_id: 23, doctor_name: 'Dr. Maya Ocampo', specialization: 'Neurology', is_active: true, active_patients: 14, current_load: 14 },
  { doctor_id: 31, doctor_name: 'Dr. Ernest Aquino', specialization: 'Orthopedics', is_active: false, active_patients: 6, current_load: 6 },
  { doctor_id: 44, doctor_name: 'Dr. Nina Cruz', specialization: 'Emergency Medicine', is_active: true, active_patients: 22, current_load: 22 },
];

export const unassignedPatients: PatientSummary[] = [
  { patient_id: 1009, full_name: 'Lian Reyes', status: 'ADMITTED', room: 'Ward 6B', condition: 'Under Observation' },
  { patient_id: 1010, full_name: 'Sofia Lim', status: 'ACTIVE', room: 'Outpatient', condition: 'Stable' },
  { patient_id: 1011, full_name: 'Miguel Santos', status: 'CRITICAL', room: 'ICU 2', condition: 'Critical' },
  { patient_id: 1012, full_name: 'Ava dela Rosa', status: 'ACTIVE', room: 'Ward 4A', condition: 'Stable' },
];

export const allAssignments: AssignmentRecord[] = [
  {
    assignment_id: 3001,
    patient_id: 1001,
    patient_name: 'Juan Dela Cruz',
    patient_status: 'ACTIVE',
    doctor_id: 12,
    doctor_name: 'Dr. Antonio Garcia',
    specialization: 'Cardiology',
    assigned_date: '2026-04-24',
    is_active: true,
    workload_count: 18,
    patient_room: 'Ward 3C',
    doctor_active_patients: 18,
    doctor_is_active: true,
    priority: 'Normal',
  },
  {
    assignment_id: 3002,
    patient_id: 1002,
    patient_name: 'Mia Santos',
    patient_status: 'ADMITTED',
    doctor_id: 17,
    doctor_name: 'Dr. Leila Santos',
    specialization: 'Pulmonology',
    assigned_date: '2026-04-19',
    is_active: true,
    workload_count: 10,
    patient_room: 'Ward 2A',
    doctor_active_patients: 10,
    doctor_is_active: true,
    priority: 'Urgent',
  },
  {
    assignment_id: 3003,
    patient_id: 1003,
    patient_name: 'Noah Villanueva',
    patient_status: 'CRITICAL',
    doctor_id: 44,
    doctor_name: 'Dr. Nina Cruz',
    specialization: 'Emergency Medicine',
    assigned_date: '2026-04-25',
    is_active: true,
    workload_count: 22,
    patient_room: 'ICU 1',
    doctor_active_patients: 22,
    doctor_is_active: true,
    priority: 'Critical',
  },
  {
    assignment_id: 3004,
    patient_id: 1004,
    patient_name: 'Luna Manalo',
    patient_status: 'ACTIVE',
    doctor_id: 23,
    doctor_name: 'Dr. Maya Ocampo',
    specialization: 'Neurology',
    assigned_date: '2026-04-18',
    is_active: false,
    workload_count: 14,
    patient_room: 'Ward 7D',
    doctor_active_patients: 14,
    doctor_is_active: true,
    priority: 'Normal',
  },
  {
    assignment_id: 3005,
    patient_id: 1005,
    patient_name: 'Ethan Cabrera',
    patient_status: 'ACTIVE',
    doctor_id: 31,
    doctor_name: 'Dr. Ernest Aquino',
    specialization: 'Orthopedics',
    assigned_date: '2026-04-21',
    is_active: true,
    workload_count: 6,
    patient_room: 'Ward 5B',
    doctor_active_patients: 6,
    doctor_is_active: false,
    priority: 'Normal',
  },
  {
    assignment_id: 3006,
    patient_id: 1006,
    patient_name: 'Sienna Cruz',
    patient_status: 'ADMITTED',
    doctor_id: 12,
    doctor_name: 'Dr. Antonio Garcia',
    specialization: 'Cardiology',
    assigned_date: '2026-04-20',
    is_active: true,
    workload_count: 18,
    patient_room: 'Ward 3A',
    doctor_active_patients: 18,
    doctor_is_active: true,
    priority: 'Urgent',
  },
  {
    assignment_id: 3007,
    patient_id: 1007,
    patient_name: 'Isla Mercado',
    patient_status: 'ACTIVE',
    doctor_id: 17,
    doctor_name: 'Dr. Leila Santos',
    specialization: 'Pulmonology',
    assigned_date: '2026-04-14',
    is_active: false,
    workload_count: 10,
    patient_room: 'Ward 2B',
    doctor_active_patients: 10,
    doctor_is_active: true,
    priority: 'Normal',
  },
];

export const specializationOptions = [
  'All',
  'Cardiology',
  'Pulmonology',
  'Neurology',
  'Orthopedics',
  'Emergency Medicine',
];

export const patientStatusOptions: PatientStatus[] = ['ACTIVE', 'ADMITTED', 'CRITICAL', 'INACTIVE'];
