services:
  postgres:
    image: postgres:16
    container_name: patienthq
    restart: always
    environment:
      POSTGRES_DB: patienthq_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"