package com.patienthq.backend.features.report.dto.request;

import com.patienthq.backend.features.report.model.ReportType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GenerateReportRequest {

    @NotNull(message = "Patient ID is required")
    private UUID patientId;

    @NotNull(message = "Generated by user ID is required")
    private UUID generatedBy;

    @NotNull(message = "Report type is required")
    private ReportType reportType;

    private String notes;
}
