import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { type ReactElement } from 'react';

interface AnalyticsChartsProps {
  monthlyReports: Array<{ month: string; value: number }>;
  appointmentOutcomes: Array<{ label: string; value: number; color: string }>;
  commonDiagnoses: Array<{ label: string; count: number }>;
  dailyActivity: Array<{ day: string; value: number }>;
  staffActivity: Array<{ label: string; value: number }>;
}

const getBarWidth = (value: number, max: number) => `${Math.max(10, (value / max) * 100)}%`;

export const AnalyticsCharts = ({ monthlyReports, appointmentOutcomes, commonDiagnoses, dailyActivity, staffActivity }: AnalyticsChartsProps): ReactElement => {
  const maxReports = Math.max(...monthlyReports.map((item) => item.value), 100);
  const maxDiagnosis = Math.max(...commonDiagnoses.map((item) => item.count), 1);
  const maxDaily = Math.max(...dailyActivity.map((item) => item.value), 1);
  const maxStaff = Math.max(...staffActivity.map((item) => item.value), 1);

  return (
    <div className="space-y-6">
      <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]">
        <Card className="rounded-3xl border-slate-200 shadow-sm">
          <CardHeader>
            <CardTitle className="text-base font-semibold text-slate-900">Reports Generated by Month</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-3">
              {monthlyReports.map((month) => (
                <div key={month.month} className="flex items-center gap-4">
                  <div className="w-16 text-sm text-slate-600">{month.month}</div>
                  <div className="relative flex-1 rounded-full bg-slate-100 h-3">
                    <div className="absolute left-0 top-0 h-3 rounded-full bg-sky-500" style={{ width: getBarWidth(month.value, maxReports) }} />
                  </div>
                  <div className="w-10 text-right text-sm font-semibold text-slate-900">{month.value}</div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card className="rounded-3xl border-slate-200 shadow-sm">
          <CardHeader>
            <CardTitle className="text-base font-semibold text-slate-900">Appointment Outcomes</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid gap-3">
              {appointmentOutcomes.map((outcome) => (
                <div key={outcome.label} className="flex items-center justify-between gap-4 text-sm">
                  <div className="flex items-center gap-3">
                    <span className={`${outcome.color} inline-block h-3 w-3 rounded-full`} />
                    <span className="text-slate-700">{outcome.label}</span>
                  </div>
                  <span className="font-semibold text-slate-900">{outcome.value}%</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 xl:grid-cols-[1.2fr_0.9fr]">
        <Card className="rounded-3xl border-slate-200 shadow-sm">
          <CardHeader>
            <CardTitle className="text-base font-semibold text-slate-900">Most Common Diagnoses</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {commonDiagnoses.map((diagnosis) => (
              <div key={diagnosis.label} className="space-y-2">
                <div className="flex items-center justify-between text-sm text-slate-700">
                  <span>{diagnosis.label}</span>
                  <span className="font-semibold text-slate-900">{diagnosis.count}</span>
                </div>
                <div className="h-2 overflow-hidden rounded-full bg-slate-100">
                  <div className="h-full rounded-full bg-emerald-500" style={{ width: getBarWidth(diagnosis.count, maxDiagnosis) }} />
                </div>
              </div>
            ))}
          </CardContent>
        </Card>

        <div className="space-y-6">
          <Card className="rounded-3xl border-slate-200 shadow-sm">
            <CardHeader>
              <CardTitle className="text-base font-semibold text-slate-900">Daily Patient Activity Trend</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-end gap-3 h-40"> 
                {dailyActivity.map((day) => (
                  <div key={day.day} className="flex-1 text-center">
                    <div className="mx-auto mb-2 h-full w-11 rounded-full bg-sky-500" style={{ height: `${(day.value / maxDaily) * 100}%` }} />
                    <div className="text-xs text-slate-500">{day.day}</div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          <Card className="rounded-3xl border-slate-200 shadow-sm">
            <CardHeader>
              <CardTitle className="text-base font-semibold text-slate-900">Staff Activity Snapshot</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {staffActivity.map((item) => (
                <div key={item.label} className="space-y-2">
                  <div className="flex items-center justify-between text-sm text-slate-700">
                    <span>{item.label}</span>
                    <span className="font-semibold text-slate-900">{item.value}</span>
                  </div>
                  <div className="h-2 overflow-hidden rounded-full bg-slate-100">
                    <div className="h-full rounded-full bg-slate-500" style={{ width: getBarWidth(item.value, maxStaff) }} />
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};