import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Button } from '@/components/ui/button';
import { type ReactElement } from 'react';
import type { ReportRecord } from '../types/report';

interface DeleteReportDialogProps {
  open: boolean;
  report: ReportRecord | null;
  onClose: () => void;
  onConfirm: (reportId: number) => void;
}

export const DeleteReportDialog = ({ open, report, onClose, onConfirm }: DeleteReportDialogProps): ReactElement => {
  if (!report) return <></>;

  return (
    <AlertDialog open={open} onOpenChange={onClose}>
      <AlertDialogContent className="max-w-md p-6">
        <AlertDialogHeader>
          <AlertDialogTitle className="text-lg font-semibold text-slate-900">Delete Report?</AlertDialogTitle>
          <AlertDialogDescription className="text-slate-600">
            This action permanently removes the report from history. Confirm only if you are authorized.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <div className="mt-4 space-y-3 rounded-3xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700">
          <div><span className="font-semibold text-slate-900">Report:</span> {report.report_type}</div>
          <div><span className="font-semibold text-slate-900">Patient:</span> {report.patient_name ?? 'Operational'}</div>
          <div><span className="font-semibold text-slate-900">Generated By:</span> {report.generated_by}</div>
        </div>
        <div className="mt-6 flex justify-end gap-2">
          <AlertDialogCancel asChild>
            <Button variant="outline">Keep Report</Button>
          </AlertDialogCancel>
          <AlertDialogAction asChild>
            <Button className="bg-red-600 text-white hover:bg-red-700" onClick={() => onConfirm(report.report_id)}>
              Delete Report
            </Button>
          </AlertDialogAction>
        </div>
      </AlertDialogContent>
    </AlertDialog>
  );
};