import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Search, Calendar, RefreshCw } from 'lucide-react';
import { type ReactElement } from 'react';

interface FilterToolbarProps<T extends string = string> {
  searchValue: string;
  onSearchChange: (value: string) => void;
  dateFrom: string;
  dateTo: string;
  onDateFromChange: (value: string) => void;
  onDateToChange: (value: string) => void;
  filters: Array<{ label: string; value: string }>;
  selectedFilter: string;
  onFilterChange: (value: string) => void;
  sortOptions: Array<{ label: string; value: string }>;
  selectedSort: T;
  onSortChange: (value: T) => void;
  secondaryFilters?: Array<{ label: string; value: string }>;
  selectedSecondaryFilter?: string;
  secondaryLabel?: string;
  onSecondaryFilterChange?: (value: string) => void;
  actions?: React.ReactNode;
  label?: string;
}

export const FilterToolbar = <T extends string = string>({
  searchValue,
  onSearchChange,
  dateFrom,
  dateTo,
  onDateFromChange,
  onDateToChange,
  filters,
  selectedFilter,
  onFilterChange,
  sortOptions,
  selectedSort,
  onSortChange,
  secondaryFilters,
  selectedSecondaryFilter,
  secondaryLabel = 'Generated By',
  onSecondaryFilterChange,
  actions,
  label = 'Search',
}: FilterToolbarProps<T>): ReactElement => (
  <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="mb-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
      <div>
        <p className="text-sm font-semibold text-slate-700">{label}</p>
        <p className="text-sm text-slate-500">Use filters to narrow reports and history events.</p>
      </div>
      <div className="flex flex-wrap items-center gap-2">{actions}</div>
    </div>

    <div className="grid gap-4 xl:grid-cols-[2fr_1fr_1fr_1fr]">
      <div className="relative">
        <Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
        <Input
          className="pl-10"
          placeholder="Search by ID, patient, or report type..."
          value={searchValue}
          onChange={(event) => onSearchChange(event.target.value)}
        />
      </div>

      <div className="grid gap-2 sm:grid-cols-2">
        <div>
          <Label className="text-sm font-medium text-slate-700 mb-2 block">From</Label>
          <Input type="date" value={dateFrom} onChange={(event) => onDateFromChange(event.target.value)} />
        </div>
        <div>
          <Label className="text-sm font-medium text-slate-700 mb-2 block">To</Label>
          <Input type="date" value={dateTo} onChange={(event) => onDateToChange(event.target.value)} />
        </div>
      </div>

      <div>
        <Label className="text-sm font-medium text-slate-700 mb-2 block">Filter</Label>
        <Select value={selectedFilter} onValueChange={onFilterChange}>
          <SelectTrigger>
            <SelectValue placeholder="Select filter" />
          </SelectTrigger>
          <SelectContent>
            {filters.map((option, index) => (
              <SelectItem key={`${option.value}-${index}`} value={option.value}>{option.label}</SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {secondaryFilters && onSecondaryFilterChange && (
        <div>
          <Label className="text-sm font-medium text-slate-700 mb-2 block">{secondaryLabel}</Label>
          <Select value={selectedSecondaryFilter} onValueChange={onSecondaryFilterChange}>
            <SelectTrigger>
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent>
              {secondaryFilters.map((option, index) => (
                <SelectItem key={`${option.value}-${index}`} value={option.value}>{option.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      )}

      {sortOptions.length > 0 && (
        <div>
          <Label className="text-sm font-medium text-slate-700 mb-2 block">Sort</Label>
          <Select value={selectedSort} onValueChange={onSortChange}>
            <SelectTrigger>
              <SelectValue placeholder="Sort" />
            </SelectTrigger>
            <SelectContent>
              {sortOptions.map((option, index) => (
                <SelectItem key={`${option.value}-${index}`} value={option.value}>{option.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      )}
    </div>

    <div className="mt-4 flex items-center gap-2">
      <Button variant="outline" size="sm" onClick={() => onSearchChange('')}>
        <RefreshCw className="h-4 w-4 mr-2" />
        Clear
      </Button>
      <Button variant="outline" size="sm" onClick={() => window.location.reload()}>
        <Calendar className="h-4 w-4 mr-2" />
        Reload
      </Button>
    </div>
  </div>
);
