import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Search, RefreshCw } from "lucide-react";
import { type ReactElement } from "react";

interface FilterToolbarProps<T extends string = string> {
  searchValue: string;
  onSearchChange: (value: string) => void;
  dateFrom: string;
  dateTo: string;
  onDateFromChange: (value: string) => void;
  onDateToChange: (value: string) => void;
  filters: Array<{ label: string; value: string }>;
  selectedFilter: string;
  onFilterChange: (value: string) => void;
  sortOptions: Array<{ label: string; value: string }>;
  selectedSort: T;
  onSortChange: (value: T) => void;
  secondaryFilters?: Array<{ label: string; value: string }>;
  selectedSecondaryFilter?: string;
  secondaryLabel?: string;
  onSecondaryFilterChange?: (value: string) => void;
  actions?: React.ReactNode;
  label?: string;
}

export const FilterToolbar = <T extends string = string>({
  searchValue,
  onSearchChange,
  dateFrom,
  dateTo,
  onDateFromChange,
  onDateToChange,
  filters,
  selectedFilter,
  onFilterChange,
  sortOptions,
  selectedSort,
  onSortChange,
  secondaryFilters,
  selectedSecondaryFilter,
  secondaryLabel = "Generated By",
  onSecondaryFilterChange,
  actions,
  label = "Search",
}: FilterToolbarProps<T>): ReactElement => (
  <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
    <div className="mb-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
      <div>
        <p className="text-sm font-semibold text-slate-700">{label}</p>
        <p className="text-sm text-slate-500">
          Use filters to narrow reports and history events.
        </p>
      </div>
      <div className="flex flex-wrap items-center gap-2">{actions}</div>
    </div>

    {/* UPDATED GRID */}
    <div className="grid gap-4 xl:grid-cols-[2fr_1.5fr_1fr_1fr_1fr_auto]">
      {/* Search */}
      <div className="relative flex items-center">
        <Search className="absolute left-3 h-4 w-4 text-slate-400" />

        <Input
          className="pl-10 h-10"
          placeholder="Search by ID, patient, or report type..."
          value={searchValue}
          onChange={(event) => onSearchChange(event.target.value)}
        />
      </div>

      {/* Date Range */}
      <div className="grid gap-2 sm:grid-cols-2">
        <div>
          <Label className="mb-2 block text-sm font-medium text-slate-700">
            From
          </Label>
          <Input
            type="date"
            value={dateFrom}
            onChange={(event) => onDateFromChange(event.target.value)}
          />
        </div>
        <div>
          <Label className="mb-2 block text-sm font-medium text-slate-700">
            To
          </Label>
          <Input
            type="date"
            value={dateTo}
            onChange={(event) => onDateToChange(event.target.value)}
          />
        </div>
      </div>

      {/* Primary Filter */}
      <div>
        <Label className="mb-2 block text-sm font-medium text-slate-700">
          Filter
        </Label>
        <Select value={selectedFilter} onValueChange={onFilterChange}>
          <SelectTrigger>
            <SelectValue placeholder="Select filter" />
          </SelectTrigger>
          <SelectContent>
            {filters.map((option, index) => (
              <SelectItem key={`${option.value}-${index}`} value={option.value}>
                {option.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Secondary Filter */}
      {secondaryFilters && onSecondaryFilterChange && (
        <div>
          <Label className="mb-2 block text-sm font-medium text-slate-700">
            {secondaryLabel}
          </Label>
          <Select
            value={selectedSecondaryFilter}
            onValueChange={onSecondaryFilterChange}
          >
            <SelectTrigger>
              <SelectValue placeholder="Select" />
            </SelectTrigger>
            <SelectContent>
              {secondaryFilters.map((option, index) => (
                <SelectItem
                  key={`${option.value}-${index}`}
                  value={option.value}
                >
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      )}

      {/* Sort */}
      {sortOptions.length > 0 && (
        <div>
          <Label className="mb-2 block text-sm font-medium text-slate-700">
            Sort
          </Label>
          <Select value={selectedSort} onValueChange={onSortChange}>
            <SelectTrigger>
              <SelectValue placeholder="Sort" />
            </SelectTrigger>
            <SelectContent>
              {sortOptions.map((option, index) => (
                <SelectItem
                  key={`${option.value}-${index}`}
                  value={option.value}
                >
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      )}

      {/* Clear Button */}
      <div className="flex items-end">
        <Button
          variant="outline"
          size="sm"
          onClick={() => onSearchChange("")}
          className="w-full"
        >
          <RefreshCw className="mr-2 h-4 w-4" />
          Clear
        </Button>
      </div>
    </div>
  </div>
);
