import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { Download, Printer, ShieldCheck } from 'lucide-react';
import { type ReactElement } from 'react';
import type { ReportRecord } from '../types/report';

interface ReportPreviewModalProps {
  open: boolean;
  onClose: () => void;
  report: ReportRecord | null;
  onDownload: (report: ReportRecord) => void;
  onPrint: (report: ReportRecord) => void;
}

export const ReportPreviewModal = ({ open, onClose, report, onDownload, onPrint }: ReportPreviewModalProps): ReactElement => {
  if (!report) return <></>;

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto p-6">
        <DialogHeader className="space-y-4">
          <div className="flex items-center justify-between gap-4">
            <div>
              <div className="text-xs uppercase tracking-[0.2em] text-slate-500">Hospital Confidential</div>
              <DialogTitle className="text-2xl font-semibold text-slate-900">{report.report_type}</DialogTitle>
              <DialogDescription className="text-sm text-slate-500">
                Preview the generated report summary before exporting or printing for authorized review.
              </DialogDescription>
            </div>
            <div className="rounded-2xl bg-slate-50 px-4 py-2 text-sm font-medium text-slate-700">
              #{report.report_id}
            </div>
          </div>
          <div className="grid gap-3 sm:grid-cols-3">
            <div>
              <div className="text-xs uppercase text-slate-500">Patient</div>
              <div className="font-medium text-slate-900">{report.patient_name ?? 'Operational'}</div>
            </div>
            <div>
              <div className="text-xs uppercase text-slate-500">Generated By</div>
              <div className="font-medium text-slate-900">{report.generated_by}</div>
            </div>
            <div>
              <div className="text-xs uppercase text-slate-500">Generated On</div>
              <div className="font-medium text-slate-900">{new Date(report.created_at).toLocaleDateString()}</div>
            </div>
          </div>
        </DialogHeader>

        <div className="rounded-3xl border border-slate-200 bg-slate-50 p-6 shadow-sm">
          <div className="mb-4 flex items-center gap-3 text-sm text-slate-600">
            <ShieldCheck className="h-4 w-4 text-slate-500" />
            Confidential summary for authorized clinical review.
          </div>
          <div className="prose prose-slate max-w-none text-sm leading-7">
            <p className='whitespace-pre-line'>{report.summary}</p>
          </div>
        </div>

        <Separator className="my-6" />

        <div className="space-y-3 text-sm text-slate-600">
          <p>This report is generated for secure clinical review and may be printed or exported only by authorized staff.</p>
          <p>Footer signature block indicates final approval by clinical operations leadership.</p>
        </div>

        <DialogFooter className="mt-4 gap-2">
          <Button variant="outline" onClick={onClose}>Close</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};