import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { MoreHorizontal, Eye, Download, Printer, Repeat, Trash2 } from 'lucide-react';
import { type ReactElement } from 'react';
import type { ReportRecord, UserRole } from '../types/report';

interface ReportsTableProps {
  reports: ReportRecord[];
  userRole: UserRole;
  onView: (report: ReportRecord) => void;
  onDownload: (report: ReportRecord) => void;
  onPrint: (report: ReportRecord) => void;
  onRegenerate: (report: ReportRecord) => void;
  onDelete: (report: ReportRecord) => void;
}

export const ReportsTable = ({
  reports,
  userRole,
  onView,
  onDownload,
  onPrint,
  onRegenerate,
  onDelete,
}: ReportsTableProps): ReactElement => {
  const canDelete = userRole === 'admin';

  return (
    <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
      <Table>
        <TableHeader>
          <TableRow className="bg-slate-50/80">
            <TableHead className="font-semibold text-slate-700">Report ID</TableHead>
            <TableHead className="font-semibold text-slate-700">Patient</TableHead>
            <TableHead className="font-semibold text-slate-700">Report Type</TableHead>
            <TableHead className="font-semibold text-slate-700">Generated By</TableHead>
            <TableHead className="font-semibold text-slate-700">Created At</TableHead>
            <TableHead className="font-semibold text-slate-700">Summary</TableHead>
            <TableHead className="font-semibold text-slate-700 w-22.5">Actions</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {reports.map((report) => (
            <TableRow key={report.report_id} className="hover:bg-slate-50/50 transition-colors">
              <TableCell className="font-medium text-slate-900">#{report.report_id}</TableCell>
              <TableCell className="text-slate-700">{report.patient_name ?? 'Operational'}</TableCell>
              <TableCell className="text-slate-700">{report.report_type}</TableCell>
              <TableCell className="text-slate-700">{report.generated_by}</TableCell>
              <TableCell className="text-slate-600">{new Date(report.created_at).toLocaleDateString()}</TableCell>
              <TableCell className="max-w-65 text-slate-600 overflow-hidden truncate">{report.summary}</TableCell>
              <TableCell>
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                      <MoreHorizontal className="h-4 w-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="w-47.5">
                    <DropdownMenuItem onClick={() => onView(report)}>
                      <Eye className="mr-2 h-4 w-4" />
                      View Report
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => onRegenerate(report)}>
                      <Repeat className="mr-2 h-4 w-4" />
                      Regenerate
                    </DropdownMenuItem>
                    {canDelete && (
                      <DropdownMenuItem onClick={() => onDelete(report)} className="text-red-600 focus:text-red-600">
                        <Trash2 className="mr-2 h-4 w-4" />
                        Delete
                      </DropdownMenuItem>
                    )}
                  </DropdownMenuContent>
                </DropdownMenu>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
      {reports.length === 0 && (
        <div className="py-12 text-center text-sm text-slate-500">No reports found for the selected criteria.</div>
      )}
    </div>
  );
};