import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { type ReactElement } from 'react';
import type { ReportRecord, UserRole } from '../types/report';
import { ReportsStatsCards } from './ReportsStatsCards';
import { FilterToolbar } from './FilterToolbar';
import { ReportsTable } from './ReportsTable';

interface ReportsTabProps {
  reports: ReportRecord[];
  filteredReports: ReportRecord[];
  userRole: UserRole;
  stats: { totalReports: number; todayReports: number; monthlyReports: number; mostRequestedType: string };
  filters: {
    search: string;
    dateFrom: string;
    dateTo: string;
    reportType: string;
    generatedBy: string;
    sortBy: 'newest' | 'oldest';
  };
  reportTypes: Array<{ label: string; value: string }>;
  generatedByOptions: Array<{ label: string; value: string }>;
  onSearchChange: (value: string) => void;
  onDateFromChange: (value: string) => void;
  onDateToChange: (value: string) => void;
  onReportTypeChange: (value: string) => void;
  onGeneratedByChange: (value: string) => void;
  onSortChange: (value: 'newest' | 'oldest') => void;
  onOpenGenerate: () => void;
  onView: (report: ReportRecord) => void;
  onDownload: (report: ReportRecord) => void;
  onPrint: (report: ReportRecord) => void;
  onRegenerate: (report: ReportRecord) => void;
  onDelete: (report: ReportRecord) => void;
}

export const ReportsTab = ({
  reports,
  filteredReports,
  userRole,
  stats,
  filters,
  reportTypes,
  generatedByOptions,
  onSearchChange,
  onDateFromChange,
  onDateToChange,
  onReportTypeChange,
  onGeneratedByChange,
  onSortChange,
  onOpenGenerate,
  onView,
  onDownload,
  onPrint,
  onRegenerate,
  onDelete,
}: ReportsTabProps): ReactElement => (
  <div className="space-y-6">
    <ReportsStatsCards
      totalReports={stats.totalReports}
      todayReports={stats.todayReports}
      monthlyReports={stats.monthlyReports}
      mostRequestedType={stats.mostRequestedType}
    />

    <FilterToolbar
      label="Report filters"
      searchValue={filters.search}
      onSearchChange={onSearchChange}
      dateFrom={filters.dateFrom}
      dateTo={filters.dateTo}
      onDateFromChange={onDateFromChange}
      onDateToChange={onDateToChange}
      filters={[
        { label: 'All Types', value: 'all' },
        ...reportTypes,
      ]}
      selectedFilter={filters.reportType}
      onFilterChange={onReportTypeChange}
      secondaryFilters={[
        { label: 'All Sources', value: 'all' },
        ...generatedByOptions,
      ]}
      selectedSecondaryFilter={filters.generatedBy}
      secondaryLabel="Generated By"
      onSecondaryFilterChange={onGeneratedByChange}
      sortOptions={[
        { label: 'Newest', value: 'newest' },
        { label: 'Oldest', value: 'oldest' },
      ]}
      selectedSort={filters.sortBy}
      onSortChange={onSortChange}
      actions={
        <Button variant="secondary" onClick={onOpenGenerate}>
          Generate Report
        </Button>
      }
    />

    <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
      <div className="text-slate-600 text-sm">Showing {filteredReports.length} of {reports.length} records</div>
      <div className="flex flex-wrap gap-2">
        <Button variant="outline" size="sm">Export Data</Button>
        <Button variant="outline" size="sm">Print</Button>
      </div>
    </div>

    <div className="hidden lg:block">
      <ReportsTable
        reports={filteredReports}
        userRole={userRole}
        onView={onView}
        onDownload={onDownload}
        onPrint={onPrint}
        onRegenerate={onRegenerate}
        onDelete={onDelete}
      />
    </div>

    <div className="lg:hidden space-y-4">
      {filteredReports.map((report) => (
        <Card key={report.report_id} className="rounded-3xl border border-slate-200 bg-white shadow-sm">
          <CardContent className="space-y-3">
            <div className="flex items-start justify-between gap-3">
              <div>
                <div className="text-sm font-semibold text-slate-900">{report.report_type}</div>
                <div className="text-sm text-slate-500">{report.patient_name ?? 'Operational'}</div>
              </div>
              <div className="text-sm text-slate-500">{new Date(report.created_at).toLocaleDateString()}</div>
            </div>
            <div className="text-sm text-slate-600">{report.summary}</div>
            <div className="flex flex-wrap gap-2">
              <Button size="sm" variant="outline" onClick={() => onView(report)}>View</Button>
              <Button size="sm" variant="outline" onClick={() => onDownload(report)}>Download</Button>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  </div>
);